# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devdebate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='writtenby',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blog_written_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debate',
            name='hostedby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foragainst',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foragainst',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topic_foragainst', to='devdebate.Debate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='opinionby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opinion_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topic_opinion', to='devdebate.Debate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinionrating',
            name='opinion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opinion_rating', to='devdebate.Debate'),
            preserve_default=False,
        ),
    ]
