# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdebate', '0002_auto_20170805_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='opinioncount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debate',
            name='stat',
            field=models.IntegerField(default=0),
        ),
    ]
