# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devdebate', '0003_auto_20170911_0320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debate',
            options={'ordering': ['-opinioncount']},
        ),
        migrations.AlterField(
            model_name='opinionrating',
            name='opinion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_rating', to='devdebate.Opinion'),
        ),
    ]
