# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdebate', '0005_opinion_legit'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
