# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devdebate', '0007_auto_20170920_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='stat',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='opinionby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
