# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devdebate', '0001_initial'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followinguser',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='followingfollowers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='activityfollow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_follow', to='UserApp.FollowingUser'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinion_list_user', to='devdebate.Debate'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='person',
            field=models.ForeignKey(default=65, on_delete=django.db.models.deletion.CASCADE, related_name='activity_of', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='supportunsupport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debate_supportunsupport', to='devdebate.ForAgainst'),
        ),
    ]
