# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20170806_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='works_at',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
