# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_person_works_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paricipation',
            field=models.IntegerField(default=0),
        ),
    ]
