# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_auto_20170806_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
