# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_auto_20170812_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
