# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_auto_20170815_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='school',
        ),
    ]
