# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdebate', '0002_auto_20170805_2359'),
        ('UserApp', '0011_remove_person_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='opinion',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='opinion',
            field=models.ManyToManyField(blank=True, null=True, to='devdebate.Opinion'),
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='supportunsupport',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='supportunsupport',
            field=models.ManyToManyField(blank=True, null=True, to='devdebate.ForAgainst'),
        ),
    ]
