# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devdebate', '0002_auto_20170805_2359'),
        ('UserApp', '0012_auto_20170818_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='supportunsupport',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='opinion',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devdebate.Opinion'),
        ),
    ]
