# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
